export const spisak = {
  KacaIFilip: {
    gender: "Dragi",
    path: "/KacaIFilip",
    name: "Katarina i Filipe",
    plural: true,
  },
  VladanaIIvan: {
    gender: "Dragi",
    path: "/VladanaIIvan",
    name: "Vladana i Ivane",
    extra: "i decu",
    plural: true,
  },
  Luka: {
    gender: "Dragi",
    path: "/Luka",
    name: "Luka",
    female: false,
  },
  VeraIBraca: {
    gender: "Dragi",
    path: "/VeraIBraca",
    name: "Mama i Tata",
    plural: true,
  },
  SnezanaINikola: {
    gender: "Dragi",
    path: "/SnezanaINikola",
    name: "Mama i Tata",
    plural: true,
  },
  Ana: {
    gender: "Draga",
    path: "/Ana",
    name: "Ana",
    female: true,
  },
  MilicaMilicevic: {
    gender: "Draga",
    path: "/MilicaMilicevic",
    name: "Milice",
    female: true,
  },
  BabaIDeda: {
    gender: "Dragi",
    path: "/BabaIDeda",
    name: "Ljubice i Ratko",
    plural: true,
  },
  SanjaIGoran: {
    gender: "Dragi",
    path: "/SanjaIGoran",
    name: "Sanja i Gorane",
    plural: true,
  },
  Danilo: {
    gender: "Dragi",
    path: "/Danilo",
    name: "Danilo",
  },
  MilicaIDario: {
    gender: "Dragi",
    path: "/MilicaIDario",
    name: "Milice i Dario",
    plural: true,
  },
  JelenaIMihajlo: {
    gender: "Draga",
    path: "/JelenaIMihajlo",
    name: "Jelena i Mihajlo",
    plural: true,
  },
  VesnaIDusan: {
    gender: "Dragi",
    path: "/VesnaIDusan",
    name: "Vesna i Dušane",
    plural: true,
  },
  NatasaIOgnjen: {
    gender: "Dragi",
    path: "/NatasaIOgnjen",
    name: "Nataša i Ognjene",
    plural: true,
  },
  Marija: {
    gender: "Draga",
    path: "/Marija",
    name: "Marija",
    female: true,
  },
  MiraIZoran: {
    gender: "Dragi",
    path: "/MiraIZoran",
    name: "Miro i Zorane",
    plural: true,
  },
  Jana: {
    gender: "Draga",
    path: "/Jana",
    name: "Jano",
    female: true,
  },
  Miroslav: {
    gender: "Dragi",
    path: "/Miroslav",
    name: "Miroslave",
  },
  Borislava: {
    gender: "Draga",
    path: "/Borislava",
    name: "Borislava",
  },
  Dragica: {
    gender: "Draga",
    path: "/Dragica",
    name: "Dragice",
  },
  JoleINidza: {
    gender: "Dragi",
    path: "/JoleINidza",
    name: "Jovana i Nikola",
    plural: true,
  },
  GagaAndChase: {
    gender: "Dear",
    path: "/GagaAndChase",
    name: "Gaga and Chase",
    english: true,
  },
  Jovan: {
    gender: "Dragi",
    path: "/Jovan",
    name: "Jovane",
  },
  Nikola: {
    gender: "Dragi",
    path: "/Nikola",
    name: "Nikola",
  },
  Zoran: {
    gender: "Dragi",
    path: "/Zoran",
    name: "Zorane",
  },
  Ivana: {
    gender: "Draga",
    path: "/Ivana",
    name: "Ivana",
    female: true,
  },
  VasilisaIMiske: {
    gender: "Dragi",
    path: "/VasilisaIMiske",
    name: "Vasilisa i Miške",
    plural: true,
  },
  Darinka: {
    gender: "Draga",
    path: "/Darinka",
    name: "Darinka",
    female: true,
  },
  SladjaIStrahinja: {
    gender: "Dragi",
    path: "/SladjaIStrahinja",
    name: "Slađo i Strahinja",
  },
  PollyAndIlija: {
    gender: "Dear",
    path: "/PollyAndIlija",
    name: "Polly and Ilija",
    english: true,
  },
  MiraIZeljko: {
    gender: "Dragi",
    path: "/MiraIZeljko",
    name: "Miro i Željko",
    plural: true,
  },
  DunjaAndJosh: {
    gender: "Dear",
    path: "/DunjaAndJosh",
    name: "Dunja and Josh",
    english: true,
  },
  AnaINikola: {
    gender: "Dragi",
    path: "/AnaINikola",
    name: "Ana i Nikola",
    plural: true,
  },
  SaraIGoran: {
    gender: "Dragi",
    path: "/SaraIGoran",
    name: "Saro i Gorane",
    plural: true,
  },
  Goca: {
    gender: "Draga",
    path: "/Goca",
    name: "Goco",
    female: true,
  },
  VanjaINiksa: {
    gender: "Dragi",
    path: "/VanjaINiksa",
    name: "Vanja i Nikša",
    plural: true,
  },
  Dzudo: {
    gender: "Dragi",
    path: "/Dzudo",
    name: "Duško",
    plural: true,
  },
  OljaYDavid: {
    gender: "Queridos",
    path: "/OljaYDavid",
    name: "Olja y David",
    spanish: true,
  },
  ValentinaIDamir: {
    gender: "Dragi",
    path: "/ValentinaIDamir",
    name: "Valentina i Damire",
    plural: true,
  },
  MitraIZoran: {
    gender: "Dragi",
    path: "/MitraIZoran",
    name: "Mitro i Zorane",
    plural: true,
  },
  Dejo: {
    gender: "Dragi",
    path: "/Dejo",
    name: "Dejane",
  },
  TamaraIAco: {
    gender: "Dragi",
    path: "/TamaraIAco",
    name: "Tamara I Aco",
    plural: true,
  },
  ZdravkoIMica: {
    gender: "Dragi",
    path: "/ZdravkoIMica",
    name: "Zdravko i Mico",
    plural: true,
  },
  MrkiIMilena: {
    gender: "Dragi",
    path: "/MrkiIMilena",
    name: "Božidare i Milena",
    plural: true,
  },
  ZoranINada: {
    gender: "Dragi",
    path: "/ZoranINada",
    name: "Zorane I Nado",
    plural: true,
  },
  Sladja: {
    gender: "Draga",
    path: "/Sladja",
    name: "Slađo",
    female: true,
  },
  Sonja: {
    gender: "Draga",
    path: "/Sonja",
    name: "Sonja",
    female: true,
  },
  Dubravka: {
    gender: "Draga",
    path: "/Dubravka",
    name: "Dubravka",
    female: true,
  },
  Ruzica: {
    gender: "Draga",
    path: "/Ruzica",
    name: "Ružice",
    female: true,
  },
  Jasna: {
    gender: "Draga",
    path: "/Jasna",
    name: "Jasna",
    female: true,
  },
  MilicaMijatov: {
    gender: "Draga",
    path: "/MilicaMijatov",
    name: "Milice",
    female: true,
  },
  Milanka: {
    gender: "Draga",
    path: "/Milanka",
    name: "Milanka",
    female: true,
  },
  Sanja: {
    gender: "Draga",
    path: "/Sanja",
    name: "Sanja",
    female: true,
  },
  SanjaIDragan: {
    plural: true,
    gender: "Dragi",
    path: "/SanjaIDragan",
    name: "Sanja i Dragane",
  },
  MilenaIMiso: {
    plural: true,
    gender: "Dragi",
    path: "/MilenaIMiso",
    name: "Milena i Mišo",
  },
  VesnaISlobo: {
    plural: true,
    gender: "Dragi",
    path: "/VesnaISlobo",
    name: "Vesna i Slobo",
  },
  DaliborkaIMiko: {
    plural: true,
    gender: "Dragi",
    path: "/DaliborkaIMiko",
    name: "Daliborka i Miko",
  },
  KatarinaIMico: {
    plural: true,
    gender: "Dragi",
    path: "/KatarinaIMico",
    name: "Katarina i Mićo",
  },
  SandraIBojan: {
    plural: true,
    gender: "Dragi",
    path: "/SandraIBojan",
    name: "Sandra i Bojane",
  },
  JelenaIDusan: {
    plural: true,
    gender: "Dragi",
    path: "/JelenaIDusan",
    name: "Jelena i Dušane",
  },
  JovanaIDragan: {
    plural: true,
    gender: "Dragi",
    path: "/JovanaIDragan",
    name: "Jovana i Dragane",
  },
  Ljilja: {
    gender: "Draga",
    path: "/Ljilja",
    name: "Ljiljo",
    female: true,
  },
  MarijaILuka: {
    plural: true,
    gender: "Dragi",
    path: "/MarijaILuka",
    name: "Marija i Luka",
  },
  BiljaIBrano: {
    plural: true,
    gender: "Dragi",
    path: "/BiljaIBrano",
    name: "Biljo i Brano",
  },
  Braco: {
    gender: "Dragi",
    path: "/Braco",
    name: "Braco",
  },
};
