export const spisak2 = {
  KacaIFilip: {
    gender: "Dragi",
    path: "/zurka/KacaIFilip",
    name: "Katarina i Filipe",
    plural: true,
  },
  MilicaIDrazen: {
    gender: "Dragi",
    path: "/zurka/MilicaIDrazen",
    name: "Milice i Dražene",
  },
  JovanaINidza: {
    gender: "Dragi",
    path: "/zurka/JovanaINidza",
    name: "Jovana i Nikola",
    plural: true,
  },
  GagaAndChase: {
    gender: "Dear",
    path: "/zurka/GagaAndChase",
    name: "Gaga and Chase",
    plural: true,
    english: true,
  },
  IvanaIZuna: {
    gender: "Dragi",
    path: "/zurka/IvanaIZuna",
    name: "Ivana i Dejane",
    plural: true,
  },
  VanjaAndBen: {
    gender: "Dear",
    path: "/zurka/VanjaAndBen",
    name: "Vanja and Ben",
    plural: true,
    english: true,
  },
  JelenaIDario: {
    gender: "Dragi",
    path: "/zurka/JelenaIDario",
    name: "Jelena i Dario",
    plural: true,
  },
  Miki: {
    gender: "Dragi",
    path: "/zurka/Miki",
    name: "Miki",
  },
  Kljaja: {
    gender: "Draga",
    path: "/zurka/Kljaja",
    name: "Aleksandra",
  },
  AnaIVladan: {
    gender: "Dragi",
    path: "/zurka/AnaIVladan",
    name: "Ana i Vladane",
    plural: true,
  },
  IrenaISrdjo: {
    gender: "Dragi",
    path: "/zurka/IrenaISrdjo",
    name: "Irena i Srđane",
    plural: true,
  },
  Nikola: {
    gender: "Dragi",
    path: "/zurka/Nikola",
    name: "Nikola",
  },
  Jovan: {
    gender: "Dragi",
    path: "/zurka/Jovan",
    name: "Jovane",
  },
  ValentinaIDamir: {
    plural: true,
    path: "/zurka/ValentinaIDamir",
    name: "Valentina i Damire",
    gender: "Dragi",
  },
  Zoran: {
    gender: "Dragi",
    path: "/zurka/Zoran",
    name: "Zorane",
  },
  NiksaIVanja: {
    gender: "Dragi",
    path: "/zurka/NiksaIVanja",
    name: "Nikša i Vanja",
    plural: true,
  },
  MinaIDanilo: {
    gender: "Dragi",
    path: "/zurka/MinaIDanilo",
    name: "Mina i Danilo",
    plural: true,
  },
  KetiIBane: {
    gender: "Dragi",
    path: "/zurka/KetiIBane",
    name: "Katarina i Bane",
    plural: true,
  },
  MarinaISrdjan: {
    gender: "Dragi",
    path: "/zurka/MarinaISrdjan",
    name: "Marina i Srđane",
    plural: true,
  },
  MarijanaIRomeo: {
    gender: "Dragi",
    path: "/zurka/MarijanaIRomeo",
    name: "Marijana i Romeo",
    plural: true,
  },
  Marko: {
    gender: "Dragi",
    path: "/zurka/Marko",
    name: "Marko",
  },
  BiljaINebojsa: {
    gender: "Dragi",
    path: "/zurka/BiljaINebojsa",
    name: "Biljo i Nebojša",
    plural: true,
  },
  Stepi: {
    gender: "Dragi",
    path: "/zurka/Stepi",
    name: "Stefane",
  },
  Uros: {
    gender: "Dragi",
    path: "/zurka/Uros",
    name: "Uroše",
  },
  IrinaIBranislav: {
    gender: "Draga",
    path: "/zurka/IrinaIBranislav",
    name: "Irina I Branislave",
  },
  OljaYDavid: {
    gender: "Queridos",
    path: "/zurka/OljaYDavid",
    name: "Olja y David",
    plural: true,
    spanish: true,
  },
  NevenaIEmir: {
    gender: "Dragi",
    path: "/zurka/NevenaIEmir",
    name: "Nevena i Emire",
    plural: true,
  },
  SaraIVlada: {
    gender: "Dragi",
    path: "/zurka/SaraIVlada",
    name: "Saro i Vlado",
    plural: true,
  },
  NeiraISuco: {
    gender: "Dragi",
    path: "/zurka/NeiraISuco",
    name: "Neira i Šuco",
    plural: true,
  },
  VasilisaIMiske: {
    gender: "Dragi",
    path: "/zurka/VasilisaIMiske",
    name: "Vasilisa i Miške",
    plural: true,
  },
  Ivana: {
    gender: "Draga",
    path: "/zurka/Ivana",
    name: "Ivana",
  },
  Darko: {
    gender: "Dragi",
    path: "/zurka/Darko",
    name: "Darko",
  },
  Dzudo: {
    gender: "Dragi",
    path: "/zurka/Dzudo",
    name: "Duško",
    plural: true,
  },
  OljaAndOliver: {
    gender: "Dear",
    path: "/zurka/OljaAndOliver",
    name: "Olja and Oliver",
    plural: true,
    english: true,
  },
  DijanaIAleksandar: {
    gender: "Dragi",
    path: "/zurka/DijanaIAleksandar",
    name: "Dijana i Aleksandre",
    plural: true,
  },
  MarijaIBoris: {
    gender: "Dragi",
    path: "/zurka/MarijaIBoris",
    name: "Marija i Borise",
    plural: true,
  },
  // JovanaiBaki: {},
  // Sneza: {},
  // Musa: {},
  // Viktor: {},
  Trobok: {},
  TeodoraILjubisa: {
    gender: "Dragi",
    path: "/zurka/TeodoraILjubisa",
    name: "Teodora i Ljubiša",
    plural: true,
  },
  Fiki: {
    gender: "Dragi",
    path: "/zurka/Fiki",
    name: "Filipe",
  },
  Panov: {},
  // Danilo: {},
  // Bilja: {},
  Micko: {
    gender: "Dragi",
    path: "/zurka/Micko",
    name: "Micko",
  },
  Dunja: {
    gender: "Draga",
    path: "/zurka/Dunja",
    name: "Dunja",
  },
  NikolaRokvic: {
    gender: "Dragi",
    path: "/zurka/NikolaRokvic",
    name: "Nikola",
    spanish: true,
  },
  NevenaISvetozar: {
    gender: "Dragi",
    path: "/zurka/NevenaISvetozar",
    name: "Nevena i Svetozar",
    plural: true,
  },
  Adri: {
    gender: "Draga",
    path: "/zurka/Adri",
    name: "Adri",
  },
};
