export const spisak = {
  KacaIFilip: {
    gender: "Dragi",
    path: "/KacaIFilip",
    name: "Katarina i Filipe",
    plural: true,
  },
  VladanaIIvan: {
    gender: "Dragi",
    path: "/VladanaIIvan",
    name: "Vladana i Ivane",
    extra: "i decu",
    plural: true,
  },
  Luka: {
    gender: "Dragi",
    path: "/Luka",
    name: "Luka",
  },
  VeraIBraca: {
    gender: "Dragi",
    path: "/VeraIBraca",
    name: "Mama i Tata",
    plural: true,
  },
  SnezanaINikola: {
    gender: "Dragi",
    path: "/SnezanaINikola",
    name: "Mama i Tata",
    plural: true,
  },
  Ana: {
    gender: "Draga",
    path: "/Ana",
    name: "Ana",
  },
  MilicaMilicevic: {
    gender: "Draga",
    path: "/MilicaMilicevic",
    name: "Milice",
  },
  BabaIDeda: {
    gender: "Dragi",
    path: "/BabaIDeda",
    name: "Ljubice i Ratko",
    plural: true,
  },
  SanjaIGoran: {
    gender: "Dragi",
    path: "/SanjaIGoran",
    name: "Sanja i Gorane",
    plural: true,
  },
  Danilo: {
    gender: "Dragi",
    path: "/Danilo",
    name: "Danilo",
  },
  MilicaIDario: {
    gender: "Dragi",
    path: "/MilicaIDario",
    name: "Milice i Dario",
    plural: true,
  },
  JelenaIMihajlo: {
    gender: "Draga",
    path: "/JelenaIMihajlo",
    name: "Jelena i Mihajlo",
  },
  VesnaIDusan: {
    gender: "Dragi",
    path: "/VesnaIDusan",
    name: "Vesna i Dušane",
    plural: true,
  },
  NatasaIOgnjen: {
    gender: "Dragi",
    path: "/NatasaIOgnjen",
    name: "Nataša i Ognjene",
    plural: true,
  },
  Marija: {
    gender: "Draga",
    path: "/Marija",
    name: "Marija",
  },
  MiraIZoran: {
    gender: "Dragi",
    path: "/MiraIZoran",
    name: "Miro i Zorane",
    plural: true,
  },
  Jana: {
    gender: "Draga",
    path: "/Jana",
    name: "Jano",
  },
  Miroslav: {
    gender: "Dragi",
    path: "/Miroslav",
    name: "Miroslave",
  },
  Borislava: {
    gender: "Draga",
    path: "/Borislava",
    name: "Borislava",
  },
  Dragica: {
    gender: "Draga",
    path: "/Dragica",
    name: "Dragice",
  },
  JoleINidza: {
    gender: "Dragi",
    path: "/JoleINidza",
    name: "Jovana i Nikola",
    plural: true,
  },
  GagaAndChase: {
    gender: "Dear",
    path: "/GagaAndChase",
    name: "Gaga and Chase",
    english: true,
  },
  Jovan: {
    gender: "Dragi",
    path: "/Jovan",
    name: "Jovane",
  },
  Nikola: {
    gender: "Dragi",
    path: "/Nikola",
    name: "Nikola",
  },
  Zoran: {
    gender: "Dragi",
    path: "/Zoran",
    name: "Zorane",
  },
  Ivana: {
    gender: "Draga",
    path: "/Ivana",
    name: "Ivana",
  },
  Miske: {
    gender: "Dragi",
    path: "/Miske",
    name: "Miške",
  },
  Darinka: {
    gender: "Draga",
    path: "/Darinka",
    name: "Darinka",
  },
  SladjaIStrahinja: {
    gender: "Dragi",
    path: "/SladjaIStrahinja",
    name: "Slađo i Strahinja",
  },
  PollyAndIlija: {
    gender: "Dear",
    path: "/PollyAndIlija",
    name: "Polly and Ilija",
    english: true,
  },
  MiraIZeljko: {
    gender: "Dragi",
    path: "/MiraIZeljko",
    name: "Miro i Željko",
    plural: true,
  },
  DunjaAndJosh: {
    gender: "Dear",
    path: "/DunjaAndJosh",
    name: "Dunja and Josh",
    english: true,
  },
  AnaINikola: {
    gender: "Dragi",
    path: "/AnaINikola",
    name: "Ana i Nikola",
    plural: true,
  },
  SaraIGoran: {
    gender: "Dragi",
    path: "/SaraIGoran",
    name: "Saro i Gorane",
    plural: true,
  },
  Goca: {
    gender: "Draga",
    path: "/Goca",
    name: "Goco",
  },
  Niksa: {
    gender: "Dragi",
    path: "/Niksa",
    name: "Nikša",
  },
  Dzudo: {
    gender: "Dragi",
    path: "/Dzudo",
    name: "Duško",
    plural: true,
  },
  OljaYDavid: {
    gender: "Queridos",
    path: "/OljaYDavid",
    name: "Olja y David",
    spanish: true,
  },
  ValentinaIDamir: {
    gender: "Dragi",
    path: "/ValentinaIDamir",
    name: "Valentina i Damire",
    plural: true,
  },
  MitraIZoran: {
    gender: "Dragi",
    path: "/MitraIZoran",
    name: "Mitro i Zorane",
    plural: true,
  },
  Dejo: {
    gender: "Dragi",
    path: "/Dejo",
    name: "Dejane",
  },
  TamaraIAco: {
    gender: "Dragi",
    path: "/TamaraIAco",
    name: "Tamara I Aco",
    plural: true,
  },
  ZdravkoIMica: {
    gender: "Dragi",
    path: "/ZdravkoIMica",
    name: "Zdravko i Mico",
    plural: true,
  },
  MrkiIMilena: {
    gender: "Dragi",
    path: "/MrkiIMilena",
    name: "Božidare i Milena",
    plural: true,
  },
  ZoranINada: {
    gender: "Dragi",
    path: "/ZoranINada",
    name: "Zorane I Nado",
    plural: true,
  },
};
